image: node:latest

services:
  - docker:dind

cache:
  paths:
    - node_modules/

.deploy-stage: &deploy-stage
  image: katomaran/node-alphine:fb-tools-16
  cache:
    key: test-monitor-ui${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/kato-internal-system/config/deploy-config.git deploy-configs
    - cp ./deploy-configs/test-monitor-system/ui/$SITE/config.json ./src/config.json
    - rm -rf deploy-configs
  script:
    - unset CI
    - npm run build
    - firebase deploy --only hosting:$HOSTING_LOCATION --token $FIREBASE_DEPLOY_KEY

#### MAIN CONFIG ####
stages:
  - npm-install
  - lint
  - build
  - deploy

eslint:
  stage: lint
  image: katomaran/node-alphine:eslint-16
  script:
    - npm run lint
  cache:
    key: test-monitor-ui${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  allow_failure: true
  only:
    - develop

install:
  stage: npm-install
  script:
    - npm install next
  cache:
    key: test-monitor-ui${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  only:
    refs:
      - develop
    changes:
      - package-lock.json

deploy:stage:
  <<: *deploy-stage
  stage: deploy
  environment: stage
  only:
    - develop
  variables:
    SITE: stage
    HOSTING_LOCATION: kato-test-monit
